import { spawn } from "node:child_process";
import { setTimeout as delay } from "node:timers/promises";
import { chromium } from "playwright-core";
const OUT = "/private/tmp/claude-501/-Users-apple-Desktop-Owed/5242465d-bb14-4655-99b8-12620fbeb506/scratchpad";
const kids = [];
const start = (c, a, env = {}) => kids.push(spawn(c, a, { env: { ...process.env, ...env }, stdio: "ignore" }));
const reach = (u) => fetch(u).then((r) => r.ok).catch(() => false);
const wait = async (u) => { for (let i = 0; i < 120; i++) { if (await reach(u)) return; await delay(300); } throw new Error("no " + u); };
start(process.execPath, ["packages/merchant-agents/dist/bin/serve.js"], { OWED_MERCHANTS_PORT: "3941" });
await wait("http://127.0.0.1:3941/merchants");
start(process.execPath, ["packages/mcp-server/dist/main.js"], { OWED_PORT: "3939", OWED_MERCHANTS_URL: "http://127.0.0.1:3941" });
await wait("http://127.0.0.1:3939/.well-known/oauth-protected-resource");
start(process.execPath, ["apps/brain/dist/main.js"], { OWED_MCP_URL: "http://127.0.0.1:3939/mcp" });
start("pnpm", ["--filter", "@owed/home", "dev"]);
await wait("http://127.0.0.1:5173/");
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1000, height: 780 } });
await page.goto("http://127.0.0.1:5173/", { waitUntil: "networkidle" });
await page.waitForSelector(".app__status--on", { timeout: 20000 });
await page.getByRole("button", { name: "Why aren't you claiming that?" }).click();
await page.waitForTimeout(2000);
const frame = page.locator("iframe.echo__screen");
await frame.screenshot({ path: `${OUT}/04-evidence.png` });
await browser.close();
for (const k of kids) k.kill("SIGTERM");
process.exit(0);
